language: ruby
rvm:
- 2.1
before_script:
- chmod +x ./cibuild
- chmod +x ./deploy
install: bundle install
script: "./cibuild"
after_success: "./deploy"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/nantescargobike/nantescargobike.github.io.git
  - secure: N48XdUDSgA4a5wX8SrP77ilJzjWdxeYHBInfl5VSu2E2cC6+5Po4Iv4PEPqs8f1g9Afkp+Tgv5IbGfDEj/rBQIqzXwxlwlXBcEVN5d7hvjaHHRkYvZwUyUoKBmUc6wrYCWgT4pIqpQfTzLTXiamkJntIwXyoCWFiSuUfW+57AutbN3CIyaa2wmOwLrMXvjsKutRK9tX0m5z7mdzzOPMo9CmQTlshpOO/yQwO5AT3ROwZzJTFiw3kgD2ci1UyfI3OD12Rj0ykx4lIecqO1a2bWT/gJmhq6BpBokOg+7O1NTJmD8Hal+CxC4NK4NShBSGHOQSE8Yq91qVuKRzbOpHjaiQ6XFMi8PNOAWot9Aja0YMqen1O7Jnw3qsFelvpWZquSP9eg6FwPFLU4emHSMB1FCO5xwKpyX+/9NIeFl9MYD2AsqVavYCiyDWc3uBmnZd4lkceTtgBS4rPZH+AjerWiNKWhb9WuBXKdV6SktgJf+wzoLvzqB/6khja+orsdK7YBPI0RcSaVD5dRNzHTvgHkpPfesG3aYfEbqGoadhVYkYYLcvNZq2aSQ6bsMOWKoC7apelUw7SdQamqRJr6lwsa7gbGRFB96SaOriycLTgSMMQ6rr4tgITKsuu9yjAyYS8legwp+bJpYvQXh415A0uVbm7GacvdPW6OeuUnCYdOsI=
