# Site settings
title: Nantes Cargo Bike
email: nantecargo@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nantescargobike.fr" # the base hostname & protocol for your site

# User setting
owner: Nantes Cargo Bike
email: nantescargo@googlegroups.com
facebook_username: nantescargo
twitter_username:
github_username:
ncb2016_address: Espl. des Traceurs de Coques 44200 Nantes France
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright: Nantes Cargo Bike

# API settings
google_api_key: AIzaSyDjA_3-WRLKA2wLNjpPVTU8o6T_5edeiWI

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
markdown_ext: "markdown, mkdown, mkdn, mkd, md"
