# Site settings
title: Nantes Cargo Bike
email: nantecargo@googlegroups.com
description: Page officielle de Nantes Cargo Bike. Association de promotion du vélo cargo dans la métropole nantaise.
author: Mathieu Ruellan <mathieu.ruellan@gmail.com>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nantescargobike.fr" # the base hostname & protocol for your site

# User setting
owner: Nantes Cargo Bike
email: nantescargo@googlegroups.com
facebook_username: nantescargo
twitter_username: nantescargobike
github_username:
ncb2016_address: Espl. des Traceurs de Coques 44200 Nantes France
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright: Nantes Cargo Bike
google_analytics_key: UA-60774720-1
# API settings
google_api_key: AIzaSyDjA_3-WRLKA2wLNjpPVTU8o6T_5edeiWI

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
markdown_ext: "markdown, mkdown, mkdn, mkd, md"
exclude: [vendor]
