#!/usr/bin/env bash
set -e # halt script on error

cd _site
rm -rf .git
git init

# inside this git repo we'll pretend to be a new user
git config user.name "Travis CI"
git config user.email "<mathieu.ruellan>@<gmail.com>"

# The first and only commit to this new Git repo contains all the
# files present with the commit message "Deploy to GitHub Pages".
git add fonts
git add CNAME
git add index.html
git add LICENSE
git add css
git add favicon.png
git add gallerie_2015
git add img
git add js
git add README.md

git commit -m "Deploy to GitHub Pages"

# Force push from the current repo's master branch to the remote
# repo's gh-pages branch. (All previous history on the gh-pages branch
# will be lost, since we are overwriting it.) We redirect any output to
# /dev/null to hide any sensitive credential data that might otherwise be exposed.
echo "GH_TOKEN=${GH_TOKEN}"
echo "GH_REF=${GH_REF}"

git push --force "https://${GH_TOKEN}@${GH_REF}" master
